### ISSUE TITLE
The dev server is running all the time, and it still requires me to log in almost every time I refresh the docs.

### ISSUE THREAD

**Issue by djpugh** [djpugh/fastapi_aad_auth#21]
@djpugh: The dev server is running all the time, and it still requires me to log in almost every time I refresh the docs.

_Originally posted by @soderluk in https://github.com/djpugh/fastapi_aad_auth/issues/16#issuecomment-734814213_

**Comment by djpugh** [comment]
cc @tricosmo

**Comment by djpugh** [comment]
Did you try: in terms of needing to login again, I'm assuming you mean when you are restarting the development server? You can set (as env variables or in a .env file):
```
SESSION_AUTH_SECRET="****"
SESSION_AUTH_SALT="****"
SESSION_SECRET="****"
```
Which will ensure restarting the server doesn't reset the cookie sessions

**Comment by djpugh** [comment]
Is the server restarting at all, or is this just on a live running server - I will check the session length defaults that they aren't too short

**Comment by tricosmo** [comment]
No, for me, the server is running all the time. no reload, or restarting. but when I refresh page, I need to authorize myself again. 
Even if I open a new tab in the same browser after authorized, it becomes unauthorized again.
 
This is know I run the server. 
```Python
    uvicorn.run(app, host='0.0.0.0', port=8000, debug=True, reload=True)
```
Again thank you very much for your time.

**Comment by djpugh** [comment]
@tricosmo - the default behaviour will re-init the session secret each reload - so with reload=True, it may well ask you to login, unless you set the session secrets as above - with those set in my .env file, it does work on reload/new tab etc.

**Comment by djpugh** [comment]
My `.env` file is:
```
AAD_CLIENT_ID=<my-client-id>
AAD_TENANT_ID=<my-tenant-id>
LOGLEVEL="DEBUG"
AAD_CLIENT_SECRET=<my-client-secret>
SESSION_AUTH_SECRET="8e1cb550-4721-4319-a9a1-2d66d10a4a2f"
SESSION_AUTH_SALT="5d56f34a-f30f-4650-8483-6420d7fcc65b"
SESSION_SECRET="5aa36ab7-3e09-4f61-a300-cb1513d88e05"
```

**Comment by djpugh** [comment]
Currently the UI based auth is via a session cookie, hence the comment above - if it is still occuring for you (this now easily persists for me across multiple restarts etc.)

**Comment by tricosmo** [comment]
Hi @djpugh, 

My problem is not even not persists after server restarts. It loses authentication just simply by refreshing the page. So you authorize, refresh page, then you need to authorize again.

I got similar .env as you
```
COMPONENT_NAME=LCR
ENV=development
DEBUG=true
LOGLEVEL="DEBUG"
AAD_CLIENT_ID = "<my_client_id>"
AAD_TENANT_ID = "<my_tenant_id>"
SESSION_AUTH_SECRET = "43cca74e-ac3f-4c42-8450-f0bcf8609b9d"
SESSION_AUTH_SALT = "14641397-9c17-439a-9b9e-e4378976c0d2"
SESSION_SECRET = "ff05f998-4799-4e45-ff3a-4e0f4fe12e35"
``` 
Code that uses `.env`
```Python
auth_provider = AADAuth()
init_oauth = auth_provider.api_auth_scheme.init_oauth
app = FastAPI(title='Fincad API', docs_url='/api/docs', swagger_ui_init_oauth=init_oauth)
```

thanks again.

**Comment by djpugh** [comment]
Hmm, are you just using this for the token validation? If you mean that you need to re-auth on the api/docs page, I think that is a function of the swagger ui - as that is all a Single Page Application, it is refreshed each time you refresh the page.

I'm not sure (but happy to look at) a way to extend that from the session auth, but if you aren't adding session auth (as in your sample above), then that won't help

**Comment by tricosmo** [comment]
> but if you aren't adding session auth (as in your sample above), 

do you mean this line 
> auth_provider = AADAuth()

I thought this will automatically config the auth session as long as I have those variables in the `.env`

It would be nice for the Single Page Application to retain authorized even after refreshing. Thanks

**Comment by djpugh** [comment]
Hi @tricosmo  - the main part of the swagger UI SPA is pure swagger UI javascript via fastapi. I have put in #32, along with some more refactoring the ability to validate against the API via the session as well, which works for me when I've logged in interactively. Beyond that I don't think there's an easy way to fix that, without going upstream to swagger UI.

To enable the session authentication, you will need to configure the fastapi app (`auth_provider.configure_app(app)`)

**Comment by tricosmo** [comment]
Hi @djpugh thank you so much. I will try it once I have time.
