### ISSUE TITLE
Does this module provide a callback, so that the user model could be persisted in the DB

### ISSUE THREAD

**Issue by djpugh** [djpugh/fastapi_aad_auth#26]
And as a bonus, does this module provide a callback, so that the user model could be persisted in the DB?

_Originally posted by @soderluk in https://github.com/djpugh/fastapi_aad_auth/issues/16#issuecomment-735724613_

**Comment by djpugh** [comment]
@soderluk - the authentication state user can be processed within the application methods - the `Depends` part of the api route returns an `AuthenticationState` object - `auth_state` in https://github.com/djpugh/fastapi_aad_auth/blob/f38dec16d29e4334347a69d95cf3e7156c4919b6/tests/testapp/server.py#L20 - and the associated user is then at `auth_state.user`

The `AADOAuthBackend` object takes a `user_klass` argument - https://github.com/djpugh/fastapi_aad_auth/blob/30018bc2ef688f7e3447d674e56e6293b542d66d/src/fastapi_aad_auth/oauth/aad.py#L16-L34 which defaults to the really basic user in https://github.com/djpugh/fastapi_aad_auth/blob/30018bc2ef688f7e3447d674e56e6293b542d66d/src/fastapi_aad_auth/oauth/state.py#L27-L39 but anything with the same interface should work

**Comment by djpugh** [comment]
@soderluk - if this makes sense, I'll add it to the documentation and close this.

**Comment by soderluk** [comment]
@djpugh Yeah, thanks, that makes sense. You could also add a snippet on how to configure that User class correctly, e.g. can you give the class as `.env` variables to the config? 

Thanks for your prompt replies, I appreciate it!
