### ISSUE TITLE
Implicit flow ? Scopes ?

### ISSUE THREAD

**Issue by Mimetis** [djpugh/fastapi_aad_auth#60]
Hello !

Is there a way to configure OpenApi to use Implicit flow ?

I need to be able to authenticate my through the OpenAPI ("/doc") interface, using the "implicit" flow:
![image](https://user-images.githubusercontent.com/4592555/120658385-b1f12f00-c485-11eb-8542-6b754992f084.png)

Today, I'm constraint to use the "authorization code" strategy (where I need to provide client id / secret) 

![image](https://user-images.githubusercontent.com/4592555/120658530-cdf4d080-c485-11eb-85cf-5523d3e5a967.png)

Other question, using the authorization code, I did not find a way to specify the scope ?
Where should I register my API scope ?

(Great work on this tool, love it :) )

**UPDATE**

Using only FastAPI, I'm able to prefill scopes and set the authentication from OpenApi, to Implicit flow, using this code

``` py
scopes = {
    "https://..../user_impersonation": "https://..../user_impersonation",
}
oauth2_scheme = OAuth2(
    flows=OAuthFlows(
        implicit=OAuthFlowImplicit(
            authorizationUrl="https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            scopes=scopes,
        )
    )
)

@app.get("/hello")
async def hello_world(token: str = Depends(oauth2_scheme)):
    print(token)
    return {"hello": "world"}

```

The idea is to know how to do the same, using your great api ?

**Comment by djpugh** [comment]
Hi @Mimetis just to check here - you are after this just for the docs/openapi portal - IIRC, you can just set the client ID, no secret required, but will have a look (under the hood this is just using the fastAPI components, so will check on the best way this weekend)

**Comment by djpugh** [comment]
@Mimetis  - so I now remember why I didn't enable too much on implicit grant - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow suggests to prefer auth code

Currently the base token validator inherits from the `OAuth2AuthorizationCodeBearer` from fastapi -
[fastapi_aad_auth._base.validators.token](https://github.com/djpugh/fastapi_aad_auth/blob/de2f1e359e468f32a10f1b45267af3c2faa60b3c/src/fastapi_aad_auth/_base/validators/token.py#L20), but I've just created a branch that has options for different auth flows - #61, which I think resolved this.

**Comment by Mimetis** [comment]
Thanks a lot ! Will take a look once the package is available on pypi
